from array import array

class VectorInt:
    def __init__(self, capacity_or_list: int | list[int]) -> None: ...
    @classmethod
    def from_array(cls, arr: array[int]) -> VectorInt: ...
    @classmethod
    def from_list(cls, ls: list[int]) -> VectorInt: ...
    def push_back(self, val: int) -> VectorInt: ...
    def extendls(self, ls: list[int]) -> None: ...
    def extendarr(self, arr: array[int]) -> None: ...
    def emplace_back(self, val: int) -> VectorInt: ...
    def emplace(self, arr: array[int]) -> VectorInt: ...
    def dot_product(self, other: VectorInt) -> int: ...
    def axpy(self, y: VectorInt, a: int) -> None: ...
    def sort(self) -> None: ...
    def find(self, key: int) -> int: ...
    def count(self, key: int) -> int: ...
    def findall(self, key: int) -> VectorInt: ...
    def sum(self) -> int: ...
    def __len__(self): ...
    def __getitem__(self, i): ...
    def __setitem__(self, i, value): ...
    def __iter__(self): ...
    def __iadd__(self, other): ...
    def __add__(self, other): ...
    def __isub__(self, other): ...
    def __sub__(self, other): ...
    def __imul__(self, other): ...
    def __mul__(self, other): ...